services:
  - type: web
    name: titi-backend
    runtime: node
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        value: TitiDB
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://titi-8b326.web.app,https://titi-8b326.firebaseapp.com
    healthCheckPath: /
    disk:
      name: titi-storage
      mountPath: /app/images
      sizeGB: 1